# develop: redis + clients_bot + sellers_bot
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
  clients_bot:
      build: .
      container_name: clients_bot
      command: uv run python -m src.bots.clients_bot.run
      env_file: 
        - .env
      depends_on:
        - redis
      volumes:
      - .:/app
      - ./logs:/app/logs
      restart: always
  sellers_bot:
    build: .
    container_name: sellers_bot
    command: uv run python -m src.bots.sellers_bot.run
    env_file: 
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: always