services:
  postgres:
    image: postgres:15
    container_name: postgres_chatbot
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: chat_bot
    ports:
      - "5433:5432"  # этот порт нужен ТОЛЬКО для твоего локального pgAdmin
    volumes:
      - .:/app
      - /Users/kirillkozlov/Desktop/telegram_chat_bot/placa-tables-7b37297f8489.json:/app/creds/placa-tables-7b37297f8489.json
      # - ./data:/app/data   # users.db
    restart: always