"""initial schema

Revision ID: b63097b3783c
Revises: 
Create Date: 2025-12-01 20:51:25.281499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63097b3783c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cabinets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('nm_id_name', sa.String(length=128), nullable=False, comment='Название ИП / магазина, вводимое пользователем'),
    sa.Column('organization_name', sa.String(length=128), nullable=False, comment='Название ИП / магазина, вводимое пользователем'),
    sa.Column('business_connection_id', sa.String(length=128), nullable=True, comment='Telegram business_connection_id для этого кабинета'),
    sa.Column('link_code', sa.String(length=64), nullable=True, comment='Код для первичной привязки бизнес-аккаунта (/link_<code>)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_code')
    )
    op.create_index(op.f('ix_cabinets_business_connection_id'), 'cabinets', ['business_connection_id'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.Integer(), nullable=False),
    sa.Column('nm_id_name', sa.String(length=256), nullable=True),
    sa.Column('photo_file_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashback_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False, comment='Кабинет, к которому относится эта таблица кэшбека'),
    sa.Column('table_id', sa.String(length=256), nullable=False, comment='Google Sheets table_id (единственный неизменяемый элемент)'),
    sa.Column('status', sa.Enum('NEW', 'PAID', 'DISABLED', 'EXPIRED', name='cashback_table_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Когда истекает оплаченный период/лимит по кэшбеку (если нужно)'),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=128), nullable=True, comment='Идентификатор платежа в ЮKassa'),
    sa.Column('service_type', sa.Enum('CASHBACK', name='payment_service_type'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True, comment='E-mail покупателя (для чеков/уведомлений)'),
    sa.Column('cashback_table_id', sa.Integer(), nullable=True, comment='Если привязываем напрямую к cashback_tables'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Сумма платежа в базовой валюте (например, в рублях или копейках — на твой выбор)'),
    sa.Column('status', sa.Enum('CREATED', 'SUCCEEDED', 'CANCELED', name='payment_status'), nullable=False),
    sa.Column('canceled_reason', sa.String(length=512), nullable=True),
    sa.Column('payment_method', sa.Enum('KIRILL_CARD', 'YOOKASSA_CARD', name='payment_method'), nullable=False),
    sa.Column('payment_type', sa.Enum('REGULAR', 'ORDINAV', name='payment_type'), nullable=False),
    sa.Column('service_data', sa.JSON(), nullable=False, comment='JSON с описанием купленного сервиса/пакета лидов'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cashback_table_id'], ['cashback_tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('cashback_tables')
    op.drop_table('articles')
    op.drop_index(op.f('ix_cabinets_business_connection_id'), table_name='cabinets')
    op.drop_table('cabinets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
