"""add_buyers_table

Revision ID: 3b30b39e9e4e
Revises: ddf3c76ccb87
Create Date: 2026-01-27 11:54:56.179261

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b30b39e9e4e"
down_revision: str | Sequence[str] | None = "ddf3c76ccb87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buyers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cabinet_id", sa.Integer(), nullable=False, comment="Кабинет продавца"),
        sa.Column("username", sa.String(length=256), nullable=True, comment="Телеграм username (без @)"),
        sa.Column("fullname", sa.String(length=512), nullable=False, comment="Полное имя пользователя в телеграме"),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False, comment="Телеграм ID покупателя"),
        sa.Column("nm_id", sa.Integer(), nullable=False, comment="Артикул товара"),
        sa.Column("is_ordered", sa.Boolean(), nullable=False, comment="Скриншот заказа принят"),
        sa.Column("is_left_feedback", sa.Boolean(), nullable=False, comment="Скриншот отзыва принят"),
        sa.Column("is_cut_labels", sa.Boolean(), nullable=False, comment="Фото разрезанных этикеток принято"),
        sa.Column("phone_number", sa.String(length=32), nullable=True, comment="Номер телефона для выплаты"),
        sa.Column("bank", sa.String(length=128), nullable=True, comment="Название банка"),
        sa.Column("amount", sa.Integer(), nullable=True, comment="Сумма кешбека в рублях"),
        sa.Column(
            "is_superbanking_paid", sa.Boolean(), nullable=False, comment="Выплата произведена через Superbanking"
        ),
        sa.Column(
            "chat_history", postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="История сообщений чата"
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["cabinet_id"], ["cabinets.id"], name=op.f("fk_buyers_cabinet_id_cabinets")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buyers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("buyers")
    # ### end Alembic commands ###
